<a href="https://colab.research.google.com/github/Aishwaryaifim/Aishu/blob/main/Copy_of_python_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")


hello world


In [ ]:
#PYTHON IS CASE SENSITIVE

In [ ]:
#[]- lists, dataframes, data extraction
#()- functions
#{}- dictoneries and sets

In [ ]:
#IN COLAB we can use ENTER for multiple purposes
# enter - Goes to next Line within same cell/code block
# ctrl + Enter - It executes this block and does not create a new block 
# shift + enter -It executes this block and goes to the next block
# Alt + Enter - It Executs this block and creates a new block

In [ ]:
#ipynb - Interactive python Book - same for colab or jupyter notebook
# is for comments 

In [ ]:
#DATA TYPES OR VARIABLE TYPES
#Integet - int 
#float / Double - Decimals -float
#string / character - Alphabets - str - it should be defined are i single code or double code("",'')
#Boolean / Logical - true or false - bool

In [ ]:
x=2                      INTEGER
type(x)

int

In [ ]:
x= 20.5                      FLOAT
type(x)

float

In [ ]:
x= 'daddy'                  STRING
type(x)

str

In [ ]:
x= True                     BOOLEAN
type(x)

bool

In [ ]:
x= False                     BOOLEAN
type(x)

bool

In [ ]:
import math                    SQUARE ROOT

In [ ]:
math.sqrt(1024)

32.0

In [ ]:
#Hierarchy of coding in python is package.<module - optional>.function()

In [ ]:
3>10    

False

In [ ]:
10+10   addition

20

In [ ]:
20-10     substraction

10

In [ ]:
20*2    multiplicatin

40

In [ ]:
20/2      division

10.0

In [ ]:
100==200   equal to

False

In [ ]:
100==100     eqal to

True

In [ ]:
100!=200    not equal

True

In [ ]:
100<200    less than

True

In [ ]:
200>100     greater than

True

In [ ]:
100<=100     lesss thant or equal to

True

In [ ]:
200>=300     more than or equal to

False

In [ ]:
test1 = 3 > 10
test2 = 3 > 1

In [ ]:
test1 | test2                 OR OPERATION

True

In [ ]:
test2 & test2                 AND OPERATION

True

In [ ]:
(3 >10) | (3>1)

True

In [ ]:
(3 > 10) & (3 > 1)

False

In [ ]:
#LOOPS
#while loop - simplest loop
#for loop    
#if condition (if, if else, nested if,)

In [ ]:
i = 0
while i <= 10:
  i = i + 1
  print(i)

1
2
3
4
5
6
7
8
9
10
11


In [ ]:
i = 7
while i <= 5:
  i = i + 1
  print(i)
  print('Thanks python')

In [ ]:
range(6)

range(0, 6)

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
for i in range(6):
  i = i + 1
  print(i)

1
2
3
4
5
6


In [ ]:
for i in range(6):
  print ("hello python : ", i)
  i = i + 1
  

hello python :  0
hello python :  1
hello python :  2
hello python :  3
hello python :  4
hello python :  5


In [ ]:
#if condition

import numpy  as np
from numpy.random import randn

In [ ]:
x = randn()
print(x)

0.06984674315220513


In [ ]:
x = randn()
result = None
if x>1:
   result = "Greater than 1"
print(x)
print(result)

-0.8717836817238366
None


In [ ]:
x = randn()
result = None
if x>1:
   result = "Greater than 1"
else:
 result = "Less than 1"
print(x)
print(result)

-1.3053245112662697
Less than 1


In [ ]:
x = randn()
if x>1:
   result = "Greater than 1"
elif x>=-1:
result = "Between -1 and 1"
else:
 result = "Less than 1"
print(x)
print(result)

IndentationError: ignored

In [ ]:
# INDENTATION IS VERY VERY IMPORTANT IN LOOPS

In [ ]:
# IN PYTHON THE INDEX STARTS FROM ZERO

In [ ]:
#lists
list1 = [10, 20.5, True, "python"]

In [ ]:
list1[0]

10

In [ ]:
list1[3]

'python'

In [ ]:
list1[2]

True

In [ ]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
list(range(1,10))           #indexing syntax starts with (start index, end index + 1, intrval)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
list(range(0,101,10))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:
list2 = list(range(20))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
list2[4]

4

In [ ]:
list2[0]

0

In [ ]:
#if you want nth item then the index will n-1

In [ ]:
list3 = ['A','B','C','D','E','F','G','H','I','J']
list3

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
list3[9]

'J'

In [ ]:
list3[4:9]

['E', 'F', 'G', 'H', 'I']

In [ ]:
list3[-1]

'J'

In [ ]:
list3[-6:-1]

['E', 'F', 'G', 'H', 'I']

In [ ]:
list3[1:9:2]

['B', 'D', 'F', 'H']

In [ ]:
list3[1:]

['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
list3[:5]

['A', 'B', 'C', 'D', 'E']

In [ ]:
list3[::2]

['A', 'C', 'E', 'G', 'I']

In [ ]:
list3[9]

'J'

In [ ]:
list3[9] = 'python'               #relpace
list3

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'python']

In [ ]:
#tuples - imutable or non changrble list

In [ ]:
tuple = (9,18,27)

In [ ]:
tuple[0]

9

In [ ]:
list[0] = 'python'                                     #in tuple not the vale is replacing so it will showing error

SyntaxError: ignored

In [ ]:
#tuple is used fou round bracate
#lists replace by square broadcasts

In [ ]:
range(30,41)

range(30, 41)

In [ ]:
list(range(30,41))

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [ ]:
mylist1 = list(range(30,41))

In [ ]:
print(mylist1)

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [ ]:
len(mylist1)

11

In [ ]:
type(mylist1)

list

In [ ]:
max(mylist1)

40

In [ ]:
min(mylist1)

30

In [ ]:
max("processwhirl")         #w=24 so max in that list

'w'

In [ ]:
min("processwhirl")         #c=3  so min in that list

'c'

In [1]:
#arrays- it hv only one type of data whlie list can have multiple type of data                      30/10/2022-sunday
#array is a list of single data type

In [2]:
import numpy as np 

In [3]:
list4 = [1,2,10,-100,200]

In [4]:
a = np.array(list4)

In [5]:
a

array([   1,    2,   10, -100,  200])

In [7]:
list5 = ['hello',9.10,36,False]

In [8]:
b = np.array(list5)

In [9]:
b

array(['hello', '9.1', '36', 'False'], dtype='<U32')

In [11]:
list6 = [9.10, 36, False]
c = np.array(list6)
c

array([ 9.1, 36. ,  0. ])

In [13]:
list7 = [36, False]
d = np.array(list7)
d

array([36,  0])

In [14]:
b= np.array([2345, 6789, 9876, 1456, -1234])

In [15]:
b.mean()

3846.4

In [16]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [17]:
b[::2]

array([ 2345,  9876, -1234])

In [18]:
c = b[2:4]

In [19]:
c

array([9876, 1456])

In [20]:
c[:] = 222

In [21]:
c

array([222, 222])

In [22]:
b

array([ 2345,  6789,   222,   222, -1234])